---
- file:
    path: /usr/src/john
    state: directory
    mode: 0700

- synchronize:
    src: files/john-1.8.0.tar.xz
    dest: /usr/src/john/john-1.8.0.tar.xz

- command: unxz john-1.8.0.tar.xz
  args:
    chdir: /usr/src/john/

- unarchive:
    src: /usr/src/john/john-1.8.0.tar
    dest: /usr/src/john/
    remote_src: True

- command: make clean linux-x86-64
  args:
    chdir: /usr/src/john/john-1.8.0/src
